
/* LIVRARIA */

CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(30),
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR CHAR(1),
	NUMERO_DE_PAGÍNAS INT(4),
	NOME_DA_EDITORA VARCHAR(20),
	VALOR_DO_LIVRO DECIMAL(10,2),
	ESTADO_DA_EDITORA CHAR(2),
	ANO_DA_PUBLICAÇÃO YEAR(4)
);
/* DADOS ADICIONADOS A TABELA */

INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Cavaleiro Real',
		'Ana Claudia',
		'F',
		465,
		'Atlas',
		'49.90',
		'RJ',
		'2009'		
);
	
INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'SQL para leigos',
		'João Nunes',
		'M',
		450,
		'Addison',
		'98.00',
		'SP',
		'2018'		
);

INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Receitas Caseiras',
		'Celia Tavares',
		'F',
		210,
		'Atlas',
		'45.00',
		'RJ',
		'2008'		
);

INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Pessoas Efetivas',
		'Eduardo Santos',
		'M',
		390,
		'Beta',
		'78.99',
		'RJ',
		'2018'		
);		

INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Habitos Saudáveis',
		'Eduardo Santos',
		'M',
		630,
		'Beta',
		'150.98',
		'RJ',
		'2019'		
);	

INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'A Casa Marrom',
		'Hermes Macedo',
		'M',
		250,
		'Bubba',
		'60.00',
		'MG',
		'2016'		
);	
	
INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Estacio Querido',
		'Geraldo Francisco',
		'M',
		310,
		'Insignia',
		'100.00',
		'ES',
		'2015'		
);	
	
INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Pra sempre amigas',
		'Leda Silva',
		'F',
		510,
		'Insignia',
		'78.98',
		'ES',
		'2011'		
);
	
INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'Copas Inesqueciveis',
		'Marco Alcantara',
		'M',
		200,
		'Larson',
		'130.98',
		'RS',
		'2018'		
);

INSERT INTO LIVROS(
		NOME_DO_LIVRO,
		NOME_DO_AUTOR,
		SEXO_DO_AUTOR,
		NUMERO_DE_PAGÍNAS,
		NOME_DA_EDITORA,
		VALOR_DO_LIVRO,
		ESTADO_DA_EDITORA,
		ANO_DA_PUBLICAÇÃO) 
	VALUES(
		'O poder da mente',
		'Clara Mafra',
		'F',
		120,
		'Continental',
		'156.58',
		'SP',
		'2018'		
);

/* 1-TRAZER TODOS OS DADOS */

SELECT * FROM LIVROS;

/* 2-TRAZER NOME DO LIVRO E EDITORA */

SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/* 3-TRAZER NOME DO LIVRO E UF DOS LIVROS PUBLICADOS POR AUTORES MASCULINOS */

SELECT NOME_DO_LIVRO, ESTADO_DA_EDITORA FROM LIVROS
	WHERE SEXO_DO_AUTOR = 'M';

/* 4-TRAZER NOME DO LIVRO E NUMERO DE PAGINA DOS LIVROS PUBLICADOS POR AUTORES FEMININOS */

SELECT NOME_DA_EDITORA, NUMERO_DE_PAGÍNAS FROM LIVROS
	WHERE SEXO_DO_AUTOR = 'F';

/* 5-TRAZER VALOR DOS LIVROS DAS EDITORAS DE SP */

SELECT VALOR_DO_LIVRO FROM LIVROS
	WHERE ESTADO_DA_EDITORA = 'SP';
	
/* 6-TRAZER OS DADOS DOS AUTORES MASCULINOS QUER TIVERAM LIVROS PUBLICADOS EM SP OU RJ */

SELECT NOME_DO_AUTOR FROM LIVROS
	WHERE SEXO_DO_AUTOR = 'M'
	AND ESTADO_DA_EDITORA = 'SP'
	OR SEXO_DO_AUTOR = 'M'
	AND ESTADO_DA_EDITORA = 'RJ'; --minha versão
	
SELECT NOME_DO_AUTOR FROM LIVROS
	WHERE SEXO_DO_AUTOR = 'M'
	AND (ESTADO_DA_EDITORA = 'SP' OR ESTADO_DA_EDITORA = 'RJ'); -- VERSÃO CORRIGIDA
	



/* exercicio */

create database exercicio;

use exercicio;

create table funcionarios
  (
      idFuncionario integer,
      nome varchar(100),
      email varchar(200),
      sexo varchar(10),
      departamento varchar(100),
      admissao varchar(10),
      salario integer,
      cargo varchar(100),
      idRegiao int
  );

/* CONSIDERANDO OQUE VC APRENDEU SOBRE PERFOMANCE, RESOLVA OS EXERCICIOS ABAIXO */

SELECT COUNT(*) FROM FUNCIONARIOS; -- CONTAR O TAMANHO DO BANCO


--Traga os funcionarios que trabalhem no departamento de filmes OU no departamento de roupas.

SELECT COUNT(*), DEPARTAMENTO --CONTAR TODOS OS DEPARTAMENTOS
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO --AGRUPAR OS DEPARTAMENTOS
ORDER BY 1; -- ORDENAR EM BASE DA PRIMEIRA COLUNA 
/*DESSA FORMA CONSEGUIMOS ANALISAR QUAL DEPARTAMENTO TEM AMIS FUNCIONARIOS ENTRE FILMES E ROUPAS,
DESSA FORMA PODEMOS DEIXAR NOSSA BUSCA MAIS PERFORMATICA EXIGINDO MENOS TRABALHO DO NOSSO BANCO*/

-- RECEBEMOS QUE TEMOS A QUANTIDADE DE FUNCIONARIOS EM CADA GRUPO 21 FILMES E 53 ROUPAS 
SELECT COUNT(*), DEPARTAMENTO 
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO 
ORDER BY 1;


SELECT NOME, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'ROUPAS' OR DEPARTAMENTO = 'FILMES'; 

--DESSE MODO A BUSCA SE TORNA MAIS PERFORMATICA POR BUSCAR PRIMEIRO A MAIOR QUANTIDADE DE RESGISTROS
--ASSIM TORNANDO A BUSCA DO 'OR' MAIS RAPIDA.

--O gestor de marketing pediu a lista das funcionarias que trabalhem no departamento de filmes OU
--no departamento de lar. Ele necessita enviar um email para as colaboradoras desses 2 setores.

SELECT NOME, SEXO, EMAIL, DEPARTAMENTO 
FROM FUNCIONARIOS
WHERE (DEPARTAMENTO = 'LAR' OR DEPARTAMENTO = 'FILMES') AND SEXO = 'FEMININO';
-- MINHA VERSÃO SOMA OS 2 DEPARTAMENTOS, E REALIZA APENAS 68 BUSCAS JÁ QUE É OBRIGATORIO FAZER AS 2 ANALISES

SELECT NOME, SEXO, EMAIL, DEPARTAMENTO 
FROM FUNCIONARIOS
WHERE
(DEPARTAMENTO = 'LAR' AND SEXO = 'FEMININO')
OR
(DEPARTAMENTO = 'FILMES' AND SEXO = 'FEMININO');
--VERSÃO CORRIGIDA FAZ AS ANALISES SEPARADAS, POREM REALIZA PRIMEIRO 47 BUSCAS, E DPS QUANDO FAZ A BUSCA DO OR
--REALIZA 31 BUSCAS E A SEÇÃO DE FILMES REALIZA 21 BUSCAS.

--Traga os funcionarios do sexo masculino ou os funcionarios que trabalhem no setor Jardim.
	
SELECT NOME, SEXO, DEPARTAMENTO 
FROM FUNCIONARIOS
WHERE SEXO = 'MASCULINO' OR DEPARTAMENTO = 'JARDIM';

--AQUI TEMOS UMA BUSCA ONDE PRECISAMOS APENAS DE UMA DAS BUSCAS VERDADEIRAS,
--E COMO TEMOS 581 OCORRENCIAS DE SEXO MASCULINO E 47 OCORROENCIAS DE SETOR JARDIM, COLOCAMOS AS MAIOR PRIMEIRO.
--ASSIM FAZENDO COM QUE A SEGUNDA ANALISE SEJÁ REPETIDA MENOS VEZES.
	
	
	
---------------------------------------------------------------------------------------------

/* EXERCICIO DE DML */	

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);


/* INSERT */


INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');
INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'77437493');
INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXX');


INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

--ENDERECOS

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ',7);

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

--TELEFONES

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);

INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',21);


/* UPDATE */

SELECT * FROM TELEFONE
SET ID_CLIENTE = 21
WHERE IDTELEFONE = 25;


UPDATE TELEFONE
SET ID_CLIENTE = 21
WHERE IDTELEFONE = 25;


/* RELATORIO GERAL DE TODOS OS CLIENTES */

SELECT C.IDCLIENTE,C.NOME, C.EMAIL, C.SEXO, C.CPF, 
	   T.NUMERO, T.TIPO, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	LEFT JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	LEFT JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE;  -- PARA TRAZER O RELATORIO DE TODOS OS FUNCIONARIOS É NECESSARIO USAR O LEFT JOIN, POIS COM O INNER JOIN NÃO TRAS OS FUNCIONARIOS QUE NÃO TENHAM TELEFONE REGISTRADO

/*
	INNER JOIN = Faz uma junção entre duas tabelas A e B onde a projeção serão todos os elementos de A que estão em B.

	LEFT JOIN = Faz uma junção entre A e B onde a projeção serão todos os elementos de A, independente se estão ou não em B.
*/

+-----------+---------+-------------------+------+-------------+----------+------+--------------------+------------+----------------+--------+
| IDCLIENTE | NOME    | EMAIL             | SEXO | CPF         | NUMERO   | TIPO | RUA                | BAIRRO     | CIDADE         | ESTADO |
+-----------+---------+-------------------+------+-------------+----------+------+--------------------+------------+----------------+--------+
|         1 | JOAO    | JOAOA@IG.COM      | M    | 76567587887 | 87866896 | CEL  | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     |
|         1 | JOAO    | JOAOA@IG.COM      | M    | 76567587887 | 99667587 | RES  | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     |
|         1 | JOAO    | JOAOA@IG.COM      | M    | 76567587887 | 66687899 | COM  | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     |
|         2 | CARLOS  | CARLOSA@IG.COM    | M    | 5464553466  | 54768899 | COM  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     |
|         2 | CARLOS  | CARLOSA@IG.COM    | M    | 5464553466  | 88687909 | CEL  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     |
|         3 | ANA     | ANA@IG.COM        | F    | 456545678   | 78989765 | CEL  | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     |
|         3 | ANA     | ANA@IG.COM        | F    | 456545678   | 99766676 | CEL  | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     |
|         4 | CLARA   | NULL              | F    | 5687766856  | NULL     | NULL | RUA ANTONIO SA     | CENTRO     | B. HORIZONTE   | MG     |
|         5 | JORGE   | JORGE@IG.COM      | M    | 8756547688  | 78458743 | CEL  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     |
|         5 | JORGE   | JORGE@IG.COM      | M    | 8756547688  | 56576876 | RES  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     |
|         5 | JORGE   | JORGE@IG.COM      | M    | 8756547688  | 89986668 | RES  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     |
|         6 | CELIA   | JCELIA@IG.COM     | M    | 5767876889  | NULL     | NULL | RUA DO OUVIDOR     | FLAMENGO   | RIO DE JANEIRO | RJ     |
|         7 | PAULA   | NULL              | F    | 77437493    | NULL     | NULL | RUA JOAQUIM SILVA  | ALVORADA   | NITEROI        | RJ     |
|         9 | FLAVIO  | FLAVIO@IG.COM     | M    | 4657765     | 68976565 | RES  | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     |
|         9 | FLAVIO  | FLAVIO@IG.COM     | M    | 4657765     | 99656675 | CEL  | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     |
|        10 | ANDRE   | ANDRE@GLOBO.COM   | M    | 7687567     | NULL     | NULL | RUA MAIA LACERDA   | ESTACIO    | RIO DE JANEIRO | RJ     |
|        11 | GIOVANA | NULL              | F    | 0876655     | 33567765 | CEL  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     |
|        11 | GIOVANA | NULL              | F    | 0876655     | 88668786 | CEL  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     |
|        11 | GIOVANA | NULL              | F    | 0876655     | 55689654 | COM  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     |
|        12 | KARLA   | KARLA@GMAIL.COM   | M    | 545676778   | 88687979 | COM  | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     |
|        13 | DANIELE | DANIELE@GMAIL.COM | M    | 43536789    | 88965676 | COM  | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     |
|        14 | LORENA  | NULL              | M    | 774557887   | NULL     | NULL | RUA CASTRO ALVES   | LEBLON     | RIO DE JANEIRO | RJ     |
|        15 | EDUARDO | NULL              | M    | 54376457    | 89966809 | CEL  | AV CAPITAO ANTUNES | CENTRO     | CURITIBA       | PR     |
|        16 | ANTONIO | ANTONIO@IG.COM    | F    | 12436767    | 88679978 | COM  | AV CARLOS BARROSO  | JARDINS    | SAO PAULO      | SP     |
|        17 | ANTONIO | ANTONIO@UOL.COM   | M    | 3423565     | 99655768 | CEL  | ALAMEDA SAMPAIO    | BOM RETIRO | CURITIBA       | PR     |
|        18 | ELAINE  | ELAINE@GLOBO.COM  | M    | 32567763    | 89955665 | RES  | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     |
|        19 | CARMEM  | CARMEM@IG.COM     | M    | 787832213   | 77455786 | RES  | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     |
|        19 | CARMEM  | CARMEM@IG.COM     | M    | 787832213   | 89766554 | RES  | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     |
|        20 | ADRIANA | ADRIANA@GMAIL.COM | F    | 88556942    | 77755785 | RES  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     |
|        21 | JOICE   | JOICE@GMAIL.COM   | F    | 55412256    | 44522578 | COM  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     |
+-----------+---------+-------------------+------+-------------+----------+------+--------------------+------------+----------------+--------+

/* RELATORIO DE HOMENS */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   T.NUMERO, T.TIPO, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	LEFT JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	LEFT JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'M';

+-----------+---------+------+-----------------+-------------+----------+------+--------------------+------------+----------------+--------+
| IDCLIENTE | NOME    | SEXO | EMAIL           | CPF         | NUMERO   | TIPO | RUA                | BAIRRO     | CIDADE         | ESTADO |
+-----------+---------+------+-----------------+-------------+----------+------+--------------------+------------+----------------+--------+
|         1 | JOAO    | M    | JOAOA@IG.COM    | 76567587887 | 87866896 | CEL  | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     |
|         1 | JOAO    | M    | JOAOA@IG.COM    | 76567587887 | 99667587 | RES  | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     |
|         1 | JOAO    | M    | JOAOA@IG.COM    | 76567587887 | 66687899 | COM  | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     |
|         2 | CARLOS  | M    | CARLOSA@IG.COM  | 5464553466  | 54768899 | COM  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     |
|         2 | CARLOS  | M    | CARLOSA@IG.COM  | 5464553466  | 88687909 | CEL  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     |
|         5 | JORGE   | M    | JORGE@IG.COM    | 8756547688  | 78458743 | CEL  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     |
|         5 | JORGE   | M    | JORGE@IG.COM    | 8756547688  | 56576876 | RES  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     |
|         5 | JORGE   | M    | JORGE@IG.COM    | 8756547688  | 89986668 | RES  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     |
|         9 | FLAVIO  | M    | FLAVIO@IG.COM   | 4657765     | 68976565 | RES  | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     |
|         9 | FLAVIO  | M    | FLAVIO@IG.COM   | 4657765     | 99656675 | CEL  | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     |
|        10 | ANDRE   | M    | ANDRE@GLOBO.COM | 7687567     | NULL     | NULL | RUA MAIA LACERDA   | ESTACIO    | RIO DE JANEIRO | RJ     |
|        15 | EDUARDO | M    | NULL            | 54376457    | 89966809 | CEL  | AV CAPITAO ANTUNES | CENTRO     | CURITIBA       | PR     |
|        17 | ANTONIO | M    | ANTONIO@UOL.COM | 3423565     | 99655768 | CEL  | ALAMEDA SAMPAIO    | BOM RETIRO | CURITIBA       | PR     |
+-----------+---------+------+-----------------+-------------+----------+------+--------------------+------------+----------------+--------+

/* ATUALIZAR CLIENTES COM DADOS ERRADOS */
ID A ATUALIZAR 6,12,13,14,18,19

SELECT IDCLIENTE, NOME, SEXO
FROM CLIENTE
WHERE IDCLIENTE = 14;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE IN (6,12,13,14,18,19); --O ATRIBUTO IN 

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 16;

/* RELATORIO DE MULHERES */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   T.NUMERO, T.TIPO, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	LEFT JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	LEFT JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F';

+-----------+---------+------+-------------------+------------+----------+------+--------------------+------------+----------------+--------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF        | NUMERO   | TIPO | RUA                | BAIRRO     | CIDADE         | ESTADO |
+-----------+---------+------+-------------------+------------+----------+------+--------------------+------------+----------------+--------+
|         3 | ANA     | F    | ANA@IG.COM        | 456545678  | 78989765 | CEL  | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678  | 99766676 | CEL  | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     |
|         4 | CLARA   | F    | NULL              | 5687766856 | NULL     | NULL | RUA ANTONIO SA     | CENTRO     | B. HORIZONTE   | MG     |
|         6 | CELIA   | F    | JCELIA@IG.COM     | 5767876889 | NULL     | NULL | RUA DO OUVIDOR     | FLAMENGO   | RIO DE JANEIRO | RJ     |
|         7 | PAULA   | F    | NULL              | 77437493   | NULL     | NULL | RUA JOAQUIM SILVA  | ALVORADA   | NITEROI        | RJ     |
|        11 | GIOVANA | F    | NULL              | 0876655    | 33567765 | CEL  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     |
|        11 | GIOVANA | F    | NULL              | 0876655    | 88668786 | CEL  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     |
|        11 | GIOVANA | F    | NULL              | 0876655    | 55689654 | COM  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     |
|        12 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778  | 88687979 | COM  | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     |
|        13 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789   | 88965676 | COM  | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     |
|        14 | LORENA  | F    | NULL              | 774557887  | NULL     | NULL | RUA CASTRO ALVES   | LEBLON     | RIO DE JANEIRO | RJ     |
|        18 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763   | 89955665 | RES  | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     |
|        19 | CARMEM  | F    | CARMEM@IG.COM     | 787832213  | 77455786 | RES  | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     |
|        19 | CARMEM  | F    | CARMEM@IG.COM     | 787832213  | 89766554 | RES  | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     |
|        20 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942   | 77755785 | RES  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     |
|        21 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256   | 44522578 | COM  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     |
+-----------+---------+------+-------------------+------------+----------+------+--------------------+------------+----------------+--------+

/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*), SEXO
FROM CLIENTE
GROUP BY SEXO;


/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULAR */

SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, 
	   T.TIPO,
	   E.BAIRRO, E.ESTADO
FROM CLIENTE C
LEFT JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND BAIRRO = 'CENTRO' AND ESTADO = 'RJ'
AND(TIPO IN ('RES','COM'));

/*PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATORIO COM 
NOME, EMAIL E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, 
	   T.NUMERO AS CELULAR,
	   E.ESTADO
FROM CLIENTE C
LEFT JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE E.ESTADO = 'RJ' AND TIPO = 'CEL';

+---------+----------------+----------+--------+
| NOME    | EMAIL          | CELULAR  | ESTADO |
+---------+----------------+----------+--------+
| JOAO    | JOAOA@IG.COM   | 87866896 | RJ     |
| CARLOS  | CARLOSA@IG.COM | 88687909 | RJ     |
| GIOVANA | NULL           | 33567765 | RJ     |
| GIOVANA | NULL           | 88668786 | RJ     |
+---------+----------------+----------+--------+

/* PARA UMA CAMPANHA DE PRODUTO DE BELEZA, O COMERCIAL SOLICITOU UM RELATORIO COM O NOME,
EMAIL, E TELEFONE CELULAR DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO */


SELECT C.NOME, C.EMAIL, 
	   T.NUMERO AS CELULAR,
	   E.ESTADO
FROM CLIENTE C
LEFT JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO ='F'
AND  E.ESTADO = 'SP'; AND TIPO = 'CEL');


/* OFICINA DO SEU JOSÉ */

/* CRIE UM BANCO CHAMADO PROJETO E SE CONECTE A ELE */

CREATE DATABASE OFICINA;

USE OFICINA;

/* FAÇA A SEGUINTE MODELAGEM:

	SR JOSÉ QUER MODERNIZAR A SUA OFICINA, E POR ENQUANTO, CADASTRA OS CARROS QUE ENTRAM PARA REALIZAR
	SERVIÇOS E SEUS RESPECTIVOS DONOS. SR JOSÉ MENCIONOU QUE CADA CLIENTE POSSUI APENAS	1 CARRO. UM 
	CARRO POSSUI UMA MARCA. SR JOSÉ TAMBEM QUER SABER AS CORES DOS CARROS PARA TER IDEIA DE QUAL TINTA 
	COMPRAR, E INFORMA QUE UM CARRO PODE TER MAIS DE UMA COR. SR JOSÉ NECESSITA ARMAZENAR OS TELEFONES 
	MAIS NÃO QUER QUE SEJAM OBRIGATORIOS.
*/

/* MODELAGEM FISICA */

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR(10),
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE 
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	PLACA VARCHAR(30) NOT NULL,
	MODELO VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR)
);

/* CONSTRAINTS */

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) 
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) 
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR) 
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO) 
REFERENCES CARRO(IDCARRO);



SELECT CONSTRAINT_SCHEMA AS "BANCO",
	   TABLE_NAME AS "TABELA",
	   CONSTRAINT_NAME AS "NOME REGRA",
	   CONSTRAINT_TYPE AS "TIPO"
	   FROM TABLE_CONSTRAINTS
	   WHERE CONSTRAINT_SCHEMA = "OFICINA";	

+---------+-----------+---------------------+-------------+
| BANCO   | TABELA    | NOME REGRA          | TIPO        |
+---------+-----------+---------------------+-------------+
| oficina | carro     | PRIMARY             | PRIMARY KEY |
| oficina | carro     | MODELO              | UNIQUE      |
| oficina | carro     | FK_CARRO_MARCA      | FOREIGN KEY |
| oficina | carro_cor | PRIMARY             | PRIMARY KEY |
| oficina | carro_cor | FK_CARRO            | FOREIGN KEY |
| oficina | carro_cor | FK_COR              | FOREIGN KEY |
| oficina | cliente   | PRIMARY             | PRIMARY KEY |
| oficina | cliente   | ID_CARRO            | UNIQUE      |
| oficina | cliente   | FK_CLIENTE_CARRO    | FOREIGN KEY |
| oficina | cor       | PRIMARY             | PRIMARY KEY |
| oficina | cor       | COR                 | UNIQUE      |
| oficina | marca     | PRIMARY             | PRIMARY KEY |
| oficina | marca     | MARCA               | UNIQUE      |
| oficina | telefone  | PRIMARY             | PRIMARY KEY |
| oficina | telefone  | FK_CLIENTE_TELEFONE | FOREIGN KEY |
+---------+-----------+---------------------+-------------+

/* INSERT MARCAS */
INSERT INTO MARCA VALUES(NULL,'CHEVROLET');
INSERT INTO MARCA VALUES(NULL,'VOLKSWAGEN');
INSERT INTO MARCA VALUES(NULL,'FIAT');
INSERT INTO MARCA VALUES(NULL,'FORD');
INSERT INTO MARCA VALUES(NULL,'HYUNDAI');
INSERT INTO MARCA VALUES(NULL,'TOYOTA');

+---------+------------+
| IDMARCA | MARCA      |
+---------+------------+
|       1 | CHEVROLET  |
|       3 | FIAT       |
|       4 | FORD       |
|       5 | HYUNDAI    |
|       6 | TOYOTA     |
|       2 | VOLKSWAGEN |
+---------+------------+

/* INSERT CORES */

INSERT INTO COR VALUES(NULL,'BRANCO');
INSERT INTO COR VALUES(NULL,'PRETO');
INSERT INTO COR VALUES(NULL,'PRATA');
INSERT INTO COR VALUES(NULL,'VERDE');
INSERT INTO COR VALUES(NULL,'AZUL');
INSERT INTO COR VALUES(NULL,'VERMELHO');

+-------+----------+
| IDCOR | COR      |
+-------+----------+
|     1 | BRANCO   |
|     2 | PRETO    |
|     3 | PRATA    |
|     4 | VERDE    |
|     5 | AZUL     |
|     6 | VERMELHO |
+-------+----------+

/* INSERT CARROS */

INSERT INTO CARRO VALUES(NULL,'ASV1234','MONZA',1);
INSERT INTO CARRO VALUES(NULL,'ARF3454','PALIO',3);
INSERT INTO CARRO VALUES(NULL,'ATH0034','UNO',3);
INSERT INTO CARRO VALUES(NULL,'BRH3194','VOYAGE',2);
INSERT INTO CARRO VALUES(NULL,'YGN8932','JETTA',2);
INSERT INTO CARRO VALUES(NULL,'LKM9901','CELTA',1);
INSERT INTO CARRO VALUES(NULL,'SDF3421','HB20',5);
INSERT INTO CARRO VALUES(NULL,'LÇK0973','ETIOS',6);
INSERT INTO CARRO VALUES(NULL,'DSF3426','GOL',2);
INSERT INTO CARRO VALUES(NULL,'OLP9064','FOCUS',4);

+---------+----------+--------+----------+
| IDCARRO | PLACA    | MODELO | ID_MARCA |
+---------+----------+--------+----------+
|       1 | ASV1234  | MONZA  |        1 |
|       2 | ARF3454  | PALIO  |        3 |
|       3 | ATH0034  | UNO    |        3 |
|       4 | BRH3194  | VOYAGE |        2 |
|       5 | YGN8932  | JETTA  |        2 |
|       6 | LKM9901  | CELTA  |        1 |
|       7 | SDF3421  | HB20   |        5 |
|       8 | LÇK0973  | ETIOS  |        6 |
|       9 | DSF3426  | GOL    |        2 |
|      10 | OLP9064  | FOCUS  |        4 |
+---------+----------+--------+----------+

/* INSERT CLIENTES */

INSERT INTO CLIENTE VALUES(NULL,'DIEGO','M',5);
INSERT INTO CLIENTE VALUES(NULL,'ANA','F',2);
INSERT INTO CLIENTE VALUES(NULL,'BARBARA','F',10);
INSERT INTO CLIENTE VALUES(NULL,'ALICE','F',8);
INSERT INTO CLIENTE VALUES(NULL,'ROBERTO','M',3);
INSERT INTO CLIENTE VALUES(NULL,'JOÃO','M',1);
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F',4);
INSERT INTO CLIENTE VALUES(NULL,'FRANCISCO','M',6);
INSERT INTO CLIENTE VALUES(NULL,'LUCIANA','F',7);
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M',9);

+-----------+-----------+------+----------+
| IDCLIENTE | NOME      | SEXO | ID_CARRO |
+-----------+-----------+------+----------+
|         1 | DIEGO     | M    |        5 |
|         2 | ANA       | F    |        2 |
|         3 | BARBARA   | F    |       10 |
|         4 | ALICE     | F    |        8 |
|         5 | ROBERTO   | M    |        3 |
|         6 | JOÃO      | M    |        1 |
|         7 | CELIA     | F    |        4 |
|         8 | FRANCISCO | M    |        6 |
|         9 | LUCIANA   | F    |        7 |
|        10 | JORGE     | M    |        9 |
+-----------+-----------+------+----------+

/* INSERT TELEFONES */

INSERT INTO TELEFONE VALUES(NULL,'1235463424','CEL',1);
INSERT INTO TELEFONE VALUES(NULL,'1904454562','RES',1);
INSERT INTO TELEFONE VALUES(NULL,'1298708984','CEL',3);
INSERT INTO TELEFONE VALUES(NULL,'1234534544','CEL',4);
INSERT INTO TELEFONE VALUES(NULL,'5645433344','RES',8);
INSERT INTO TELEFONE VALUES(NULL,'1235463424','CEL',10);
INSERT INTO TELEFONE VALUES(NULL,'0786556345','CEL',9);
INSERT INTO TELEFONE VALUES(NULL,'7689055675','COM',9);
INSERT INTO TELEFONE VALUES(NULL,'0656734563','CEL',6);
INSERT INTO TELEFONE VALUES(NULL,'9768678567','RES',6);
INSERT INTO TELEFONE VALUES(NULL,'3242346784','CEL',2);

/* INSERT CARRO_COR */

INSERT INTO CARRO_COR VALUES(1,3);
INSERT INTO CARRO_COR VALUES(2,3);
INSERT INTO CARRO_COR VALUES(3,2);
INSERT INTO CARRO_COR VALUES(4,6);
INSERT INTO CARRO_COR VALUES(5,4);
INSERT INTO CARRO_COR VALUES(6,5);
INSERT INTO CARRO_COR VALUES(7,2);
INSERT INTO CARRO_COR VALUES(8,1);
INSERT INTO CARRO_COR VALUES(9,4);
INSERT INTO CARRO_COR VALUES(10,3);

+----------+--------+
| ID_CARRO | ID_COR |
+----------+--------+
|        1 |      3 |
|        2 |      3 |
|        3 |      2 |
|        4 |      6 |
|        5 |      4 |
|        6 |      5 |
|        7 |      2 |
|        8 |      1 |
|        9 |      4 |
|       10 |      3 |
+----------+--------+

/* SELECT DE DADOS DA TABELA */

SELECT  NOME, SEXO,
		PLACA, MODELO,
		MARCA,
		IFNULL(NUMERO,'NÃO INFORMADO')AS 'TELEFONE', IFNULL(TIPO,'***') AS 'TIPO'
	FROM CLIENTE
	LEFT JOIN CARRO
	ON ID_CARRO = IDCARRO
	LEFT JOIN TELEFONE
	ON IDCLIENTE = ID_CLIENTE
	LEFT JOIN MARCA
	ON IDMARCA = ID_MARCA;

+-----------+------+----------+--------+------------+----------------+------+
| NOME      | SEXO | PLACA    | MODELO | MARCA      | TELEFONE       | TIPO |
+-----------+------+----------+--------+------------+----------------+------+
| DIEGO     | M    | YGN8932  | JETTA  | VOLKSWAGEN | 1235463424     | CEL  |
| DIEGO     | M    | YGN8932  | JETTA  | VOLKSWAGEN | 1904454562     | RES  |
| ANA       | F    | ARF3454  | PALIO  | FIAT       | 3242346784     | CEL  |
| BARBARA   | F    | OLP9064  | FOCUS  | FORD       | 1298708984     | CEL  |
| ALICE     | F    | LÇK0973  | ETIOS  | TOYOTA     | 1234534544     | CEL  |
| ROBERTO   | M    | ATH0034  | UNO    | FIAT       | NÃO INFORMADO  | ***  |
| JOÃO      | M    | ASV1234  | MONZA  | CHEVROLET  | 0656734563     | CEL  |
| JOÃO      | M    | ASV1234  | MONZA  | CHEVROLET  | 9768678567     | RES  |
| CELIA     | F    | BRH3194  | VOYAGE | VOLKSWAGEN | NÃO INFORMADO  | ***  |
| FRANCISCO | M    | LKM9901  | CELTA  | CHEVROLET  | 5645433344     | RES  |
| LUCIANA   | F    | SDF3421  | HB20   | HYUNDAI    | 0786556345     | CEL  |
| LUCIANA   | F    | SDF3421  | HB20   | HYUNDAI    | 7689055675     | COM  |
| JORGE     | M    | DSF3426  | GOL    | VOLKSWAGEN | 1235463424     | CEL  |
+-----------+------+----------+--------+------------+----------------+------+
/* FALTA O RELATORIO QUE TRAZ A COR DO CARRO JUNTO COM TODO OS DADOS */

SELECT  C.NOME, C.SEXO,
		CA.PLACA, CA.MODELO,
		M.MARCA,
		CO.COR,
		IFNULL(T.NUMERO,'NÃO INFORMADO')AS 'TELEFONE', IFNULL(T.TIPO,'***') AS 'TIPO'
	FROM CLIENTE C
	LEFT JOIN CARRO CA
	ON C.ID_CARRO = CA.IDCARRO
	LEFT JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	LEFT JOIN MARCA M
	ON M.IDMARCA = CA.ID_MARCA
	LEFT JOIN CARRO_COR CAO
	ON CA.IDCARRO = CAO.ID_CARRO
	LEFT JOIN COR CO
	ON CO.IDCOR = CAO.ID_COR;

+-----------+------+----------+--------+------------+----------+----------------+------+
| NOME      | SEXO | PLACA    | MODELO | MARCA      | COR      | TELEFONE       | TIPO |
+-----------+------+----------+--------+------------+----------+----------------+------+
| DIEGO     | M    | YGN8932  | JETTA  | VOLKSWAGEN | VERDE    | 1235463424     | CEL  |
| DIEGO     | M    | YGN8932  | JETTA  | VOLKSWAGEN | VERDE    | 1904454562     | RES  |
| ANA       | F    | ARF3454  | PALIO  | FIAT       | PRATA    | 3242346784     | CEL  |
| BARBARA   | F    | OLP9064  | FOCUS  | FORD       | PRATA    | 1298708984     | CEL  |
| ALICE     | F    | LÇK0973  | ETIOS  | TOYOTA     | BRANCO   | 1234534544     | CEL  |
| ROBERTO   | M    | ATH0034  | UNO    | FIAT       | PRETO    | NÃO INFORMADO  | ***  |
| JOÃO      | M    | ASV1234  | MONZA  | CHEVROLET  | PRATA    | 0656734563     | CEL  |
| JOÃO      | M    | ASV1234  | MONZA  | CHEVROLET  | PRATA    | 9768678567     | RES  |
| CELIA     | F    | BRH3194  | VOYAGE | VOLKSWAGEN | VERMELHO | NÃO INFORMADO  | ***  |
| FRANCISCO | M    | LKM9901  | CELTA  | CHEVROLET  | AZUL     | 5645433344     | RES  |
| LUCIANA   | F    | SDF3421  | HB20   | HYUNDAI    | PRETO    | 0786556345     | CEL  |
| LUCIANA   | F    | SDF3421  | HB20   | HYUNDAI    | PRETO    | 7689055675     | COM  |
| JORGE     | M    | DSF3426  | GOL    | VOLKSWAGEN | VERDE    | 1235463424     | CEL  |
+-----------+------+----------+--------+------------+----------+----------------+------+
































